# permissions for end users to edit queryexporters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: queryexporter-editor-role
rules:
- apiGroups:
  - exporters.curuvija.com
  resources:
  - queryexporters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - exporters.curuvija.com
  resources:
  - queryexporters/status
  verbs:
  - get
