apiVersion: exporters.curuvija.com/v1alpha1
kind: QueryExporter
metadata:
  name: queryexporter-sample
spec:
  # Default values copied from <project_dir>/helm-charts/query-exporter/values.yaml
  affinity: {}
  autoscaling:
    enabled: false
    maxReplicas: 100
    minReplicas: 1
    targetCPUUtilizationPercentage: 80
  config: |-
    databases:
      db1:
        dsn: sqlite://
        connect-sql:
          - PRAGMA application_id = 123
          - PRAGMA auto_vacuum = 1
        labels:
          region: us1
          app: app1
  
    metrics:
      metric1:
        type: gauge
        description: A sample gauge
  
    queries:
      query1:
        interval: 5
        databases: [db1]
        metrics: [metric1]
        sql: SELECT random() / 1000000000000000 AS metric1
  fullnameOverride: ""
  image:
    pullPolicy: IfNotPresent
    repository: adonato/query-exporter
    tag: ""
  imagePullSecrets: []
  ingress:
    annotations: {}
    className: ""
    enabled: false
    hosts:
    - host: chart-example.local
      paths:
      - path: /
        pathType: ImplementationSpecific
    tls: []
  livenessProbe:
    httpGet:
      path: /
      port: 9560
  nameOverride: ""
  nodeSelector: {}
  podAnnotations: {}
  podSecurityContext: {}
  prometheus:
    monitor:
      additionalLabels: {}
      enabled: true
      interval: 15s
      namespace: []
      path: /metrics
  readinessProbe:
    httpGet:
      path: /
      port: 9560
  replicaCount: 1
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi
  securityContext:
    readOnlyRootFilesystem: true
    runAsNonRoot: true
    runAsUser: 1000
  service:
    port: 9560
    type: ClusterIP
  serviceAccount:
    annotations: {}
    create: true
    name: ""
  tolerations: []
  
  
